### ISSUE TITLE
Link to `nose` in docs outdated

### ISSUE THREAD

**Issue by pyhedgehog** [ponty/psidialogs#4]
In [links.rst#L7](https://github.com/ponty/psidialogs/blob/62656516b550cbcae7efd4680c800d25c8999469/docs/links.rst#L7) there are incorrect link to `nose` project. Current documentation can be found on https://nose.readthedocs.io/en/latest/. More permanent link seems to be http://packages.python.org/nose/.

**Comment by ponty** [comment]
Thanks. I removed the link, I use pytest instead.
